//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package azopenai

const (
	endpoint = ""
	moduleName = "azopenai"
	moduleVersion = "v0.0.1"
)

// Post200ApplicationJSONPropertiesItemsMessageRole - The role of the author of this message.
type Post200ApplicationJSONPropertiesItemsMessageRole string

const (
	Post200ApplicationJSONPropertiesItemsMessageRoleAssistant Post200ApplicationJSONPropertiesItemsMessageRole = "assistant"
	Post200ApplicationJSONPropertiesItemsMessageRoleSystem Post200ApplicationJSONPropertiesItemsMessageRole = "system"
	Post200ApplicationJSONPropertiesItemsMessageRoleUser Post200ApplicationJSONPropertiesItemsMessageRole = "user"
)

// PossiblePost200ApplicationJSONPropertiesItemsMessageRoleValues returns the possible values for the Post200ApplicationJSONPropertiesItemsMessageRole const type.
func PossiblePost200ApplicationJSONPropertiesItemsMessageRoleValues() []Post200ApplicationJSONPropertiesItemsMessageRole {
	return []Post200ApplicationJSONPropertiesItemsMessageRole{
		Post200ApplicationJSONPropertiesItemsMessageRoleAssistant,
		Post200ApplicationJSONPropertiesItemsMessageRoleSystem,
		Post200ApplicationJSONPropertiesItemsMessageRoleUser,
	}
}

// PostRequestBodyContentApplicationJSONSchemaMessagesItemRole - The role of the author of this message.
type PostRequestBodyContentApplicationJSONSchemaMessagesItemRole string

const (
	PostRequestBodyContentApplicationJSONSchemaMessagesItemRoleAssistant PostRequestBodyContentApplicationJSONSchemaMessagesItemRole = "assistant"
	PostRequestBodyContentApplicationJSONSchemaMessagesItemRoleSystem PostRequestBodyContentApplicationJSONSchemaMessagesItemRole = "system"
	PostRequestBodyContentApplicationJSONSchemaMessagesItemRoleUser PostRequestBodyContentApplicationJSONSchemaMessagesItemRole = "user"
)

// PossiblePostRequestBodyContentApplicationJSONSchemaMessagesItemRoleValues returns the possible values for the PostRequestBodyContentApplicationJSONSchemaMessagesItemRole const type.
func PossiblePostRequestBodyContentApplicationJSONSchemaMessagesItemRoleValues() []PostRequestBodyContentApplicationJSONSchemaMessagesItemRole {
	return []PostRequestBodyContentApplicationJSONSchemaMessagesItemRole{
		PostRequestBodyContentApplicationJSONSchemaMessagesItemRoleAssistant,
		PostRequestBodyContentApplicationJSONSchemaMessagesItemRoleSystem,
		PostRequestBodyContentApplicationJSONSchemaMessagesItemRoleUser,
	}
}

