//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package azopenai

const (
	endpoint      = ""
	moduleName    = "azopenai"
	moduleVersion = "v0.0.1"
)

// ChatCompletionsMessageRole - The role of the author of this message.
type ChatCompletionsMessageRole string

const (
	ChatCompletionsMessageRoleAssistant ChatCompletionsMessageRole = "assistant"
	ChatCompletionsMessageRoleSystem    ChatCompletionsMessageRole = "system"
	ChatCompletionsMessageRoleUser      ChatCompletionsMessageRole = "user"
)

// PossibleChatCompletionsMessageRoleValues returns the possible values for the ChatCompletionsMessageRole const type.
func PossibleChatCompletionsMessageRoleValues() []ChatCompletionsMessageRole {
	return []ChatCompletionsMessageRole{
		ChatCompletionsMessageRoleAssistant,
		ChatCompletionsMessageRoleSystem,
		ChatCompletionsMessageRoleUser,
	}
}
